### ISSUE TITLE
Unable to login after updating to 1.2.0

### ISSUE THREAD

**Issue by mzch** [polonel/trudesk#490]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Unable to login.

**What did you expect to happen**:
Login successfully.

**How to reproduce it (as minimally and precisely as possible)**:
- `git pull`
- `yarn install`
- `yarn build`
- `yarn start`
- visit login page and enter login credenantials.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: `1.2.0`
- OS (e.g. from /etc/os-release): Debian `11.3`
- Node.JS Version: `v16.14.2`
- MongoDB Version: `5.1`
- Is this hosted on cloud.trudesk.io: no

**Log**
```
Apr 10 00:48:56 n21 yarn[1235]: Error: Cannot find module '../encodings'
Apr 10 00:48:56 n21 yarn[1235]: Require stack:
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/node_modules/raw-body/node_modules/iconv-lite/lib/index.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/node_modules/raw-body/index.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/node_modules/body-parser/lib/read.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/node_modules/body-parser/lib/types/json.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/node_modules/body-parser/index.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/node_modules/express/lib/express.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/node_modules/express/index.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/src/webserver.js
Apr 10 00:48:56 n21 yarn[1235]: - /srv/trudesk/trudesk/app.js
Apr 10 00:48:56 n21 yarn[1235]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Apr 10 00:48:56 n21 yarn[1235]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Apr 10 00:48:56 n21 yarn[1235]:     at Module.require (internal/modules/cjs/loader.js:887:19)
Apr 10 00:48:56 n21 yarn[1235]:     at require (internal/modules/cjs/helpers.js:74:18)
Apr 10 00:48:56 n21 yarn[1235]:     at Object.getCodec (/srv/trudesk/trudesk/node_modules/raw-body/node_modules/iconv-lite/lib/index.js:65:27)
Apr 10 00:48:56 n21 yarn[1235]:     at Object.getDecoder (/srv/trudesk/trudesk/node_modules/raw-body/node_modules/iconv-lite/lib/index.js:127:23)
Apr 10 00:48:56 n21 yarn[1235]:     at getDecoder (/srv/trudesk/trudesk/node_modules/raw-body/index.js:45:18)
Apr 10 00:48:56 n21 yarn[1235]:     at readStream (/srv/trudesk/trudesk/node_modules/raw-body/index.js:180:15)
Apr 10 00:48:56 n21 yarn[1235]:     at getRawBody (/srv/trudesk/trudesk/node_modules/raw-body/index.js:108:12)
Apr 10 00:48:56 n21 yarn[1235]:     at read (/srv/trudesk/trudesk/node_modules/body-parser/lib/read.js:77:3)
Apr 10 00:48:56 n21 yarn[1235]:     at urlencodedParser (/srv/trudesk/trudesk/node_modules/body-parser/lib/types/urlencoded.js:116:5)
Apr 10 00:48:56 n21 yarn[1235]:     at Layer.handle [as handle_request] (/srv/trudesk/trudesk/node_modules/express/lib/router/layer.js:95:5)
Apr 10 00:48:56 n21 yarn[1235]:     at trim_prefix (/srv/trudesk/trudesk/node_modules/express/lib/router/index.js:317:13)
Apr 10 00:48:56 n21 yarn[1235]:     at /srv/trudesk/trudesk/node_modules/express/lib/router/index.js:284:7
Apr 10 00:48:56 n21 yarn[1235]:     at Function.process_params (/srv/trudesk/trudesk/node_modules/express/lib/router/index.js:335:12)
Apr 10 00:48:56 n21 yarn[1235]:     at next (/srv/trudesk/trudesk/node_modules/express/lib/router/index.js:275:10)
Apr 10 00:48:56 n21 yarn[1235]:     at expressInit (/srv/trudesk/trudesk/node_modules/express/lib/middleware/init.js:40:5)
Apr 10 00:48:56 n21 yarn[1235]:     at Layer.handle [as handle_request] (/srv/trudesk/trudesk/node_modules/express/lib/router/layer.js:95:5)
Apr 10 00:48:56 n21 yarn[1235]:     at trim_prefix (/srv/trudesk/trudesk/node_modules/express/lib/router/index.js:317:13)
Apr 10 00:48:56 n21 yarn[1235]:     at /srv/trudesk/trudesk/node_modules/express/lib/router/index.js:284:7
Apr 10 00:48:56 n21 yarn[1235]:     at Function.process_params (/srv/trudesk/trudesk/node_modules/express/lib/router/index.js:335:12)
Apr 10 00:48:56 n21 yarn[1235]:     at next (/srv/trudesk/trudesk/node_modules/express/lib/router/index.js:275:10)
```

**Comment by mzch** [comment]
This issue is fixed by `cd node_modules/raw-body && npm install`.

**Comment by polonel** [comment]
With all the packages that were updated in this release, it's probably best to remove `node_modules` altogether and run `yarn install`
